# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
