# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0003_auto_20160206_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalgoal',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='virturalgoal',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='physicalgoal',
            name='datetime',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='virturalgoal',
            name='datetime',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
