# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0005_auto_20160206_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='url',
            field=models.CharField(default='', max_length=10),
        ),
    ]
