# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0006_campaign_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirturalGoal',
            new_name='VirtualGoal',
        ),
    ]
