# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0007_auto_20160206_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalgoal',
            old_name='compaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='virtualgoal',
            old_name='compaign',
            new_name='campaign',
        ),
    ]
